### PR TITLE
Completed PreCourse - 1 -> Please Review

### PR DESCRIPTION
**Pull request by mohit9494**

### CODE REVIEW

**Review by niharikagupta2021 — COMMENTED** [review]
Good Job! Please check space complexity for all problems

**Comment by niharikagupta2021** [comment]
Good Job! Please check space complexity for all problems

**Comment by mohit9494** [comment]
If we are designing a data structure, are we supposed to consider Space complexity? 
For example, if we are using a dynamic array (resizing) as our base datastructure.

**Comment by niharikagupta2021** [comment]
yes. You should consider any extra/auxiliary space you are using in your solution

**Pull request closed without merging**
